import { ArrowRight, Clock3, ListChecks, UserCheck, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Card } from "@/components/ux/Card";
import { cn } from "@/lib/utils";
import type { WorkloadData } from "../types/recruiterAnalytics";
import { AnalyticsEmptyState } from "./AnalyticsEmptyState";
export function WorkloadPanel({ data }: { data: WorkloadData }) {
  const navigate = useNavigate();
  const actions = [["CV mới cần sàng lọc",data.actions.cvsToScreen,Users],["Ứng viên quá SLA",data.actions.candidatesOverSla,Clock3],["Đánh giá chờ duyệt",data.actions.assessmentsPendingReview,ListChecks],["Phỏng vấn trong 48 giờ",data.actions.upcomingInterviews,UserCheck]] as const;
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{actions.map(([title,count,Icon]) => <Card key={title} className="p-4"><span className="grid size-10 place-items-center rounded-xl bg-[var(--color-primary-soft)] text-brand-primary"><Icon className="size-5" aria-hidden="true" /></span><p className="mt-4 text-3xl font-semibold">{count}</p><h2 className="mt-1 text-sm font-semibold">{title}</h2></Card>)}</div>{data.jobs.length === 0 ? <AnalyticsEmptyState>Chưa có vị trí nào được phân công cho bạn trong kỳ này.</AnalyticsEmptyState> : <Card className="overflow-hidden p-0"><h2 className="px-5 py-4 font-display text-lg font-semibold">Vị trí cần chú ý</h2>{data.jobs.map((job) => <div key={job.jobId} className="grid gap-4 border-t border-[var(--color-border-default)] px-5 py-4 md:grid-cols-[1fr_150px_120px_auto] md:items-center"><div><h3 className="font-semibold">{job.title}</h3><p className="text-xs text-[var(--color-text-secondary)]">{job.candidateCount} ứng viên · {job.currentFocusStage ?? "Chưa có vòng"}</p></div><div><div className="flex justify-between text-xs"><span>Độ khỏe</span><strong>{job.healthScore}%</strong></div><div className="mt-1 h-2 rounded-full bg-surface-muted"><div className="h-full rounded-full bg-brand-primary" style={{width:`${job.healthScore}%`}} /></div></div><span className={cn("w-fit rounded-full px-2.5 py-1 text-xs font-semibold",job.overdueCount?"bg-amber-100 text-amber-800":"bg-[var(--color-primary-soft)] text-brand-primary")}>{job.overdueCount} quá SLA</span><button type="button" onClick={() => navigate(`/recruiter/pipeline?jobId=${job.jobId}`)} className="inline-flex min-h-10 items-center gap-1 rounded-lg px-2 text-sm font-semibold text-brand-primary hover:bg-[var(--color-primary-soft)]">Xem pipeline <ArrowRight className="size-4" aria-hidden="true" /></button></div>)}</Card>}</div>;
}
