-- V11: Create contracts table for B2B e-Contract and Digital Signing
CREATE TABLE IF NOT EXISTS contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    plan_id BIGINT NULL,
    consultation_request_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    contract_value DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    signer_name VARCHAR(255) NOT NULL,
    signer_email VARCHAR(255) NOT NULL,
    signer_title VARCHAR(255) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    sign_method VARCHAR(32) NULL,
    signed_at TIMESTAMP NULL,
    signed_document_url VARCHAR(512) NULL,
    document_checksum VARCHAR(128) NULL,
    terms_and_conditions TEXT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contract_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_contract_plan FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE SET NULL,
    CONSTRAINT fk_contract_lead FOREIGN KEY (consultation_request_id) REFERENCES consultation_requests(id) ON DELETE SET NULL
);

CREATE INDEX idx_contracts_tenant ON contracts (tenant_id);
CREATE INDEX idx_contracts_status ON contracts (status);
CREATE INDEX idx_contracts_number ON contracts (contract_number);
