-- V13: Enhance Master Schema for Scale

-- 1. Convert TEXT to JSONB for PostgreSQL specific optimization
ALTER TABLE platform_audit_logs ALTER COLUMN metadata_json TYPE JSONB USING metadata_json::jsonb;
ALTER TABLE subscription_plans ALTER COLUMN features_json TYPE JSONB USING features_json::jsonb;

-- 2. Add Soft Delete
ALTER TABLE tenants 
    ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE subscription_plans 
    ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

-- 3. Create invoice_line_items table
CREATE TABLE IF NOT EXISTS invoice_line_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(10,2) NOT NULL,
    total_price DECIMAL(10,2) NOT NULL,
    item_type VARCHAR(64) NOT NULL DEFAULT 'BASE_PLAN',
    CONSTRAINT fk_ili_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_invoice_line_items_invoice_id ON invoice_line_items(invoice_id);

-- 4. Create contract_signatures table and remove OTP fields from contracts
CREATE TABLE IF NOT EXISTS contract_signatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    signer_name VARCHAR(255) NOT NULL,
    signer_email VARCHAR(255) NOT NULL,
    signer_title VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    signed_at TIMESTAMP NULL,
    otp_code VARCHAR(10) NULL,
    otp_expires_at TIMESTAMP NULL,
    client_ip VARCHAR(64) NULL,
    CONSTRAINT fk_cs_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_contract_signatures_contract_id ON contract_signatures(contract_id);

ALTER TABLE contracts 
    DROP COLUMN IF EXISTS otp_code,
    DROP COLUMN IF EXISTS otp_expires_at;
