-- V14: System Settings and Dynamic AI Engine Configurations

CREATE TABLE IF NOT EXISTS system_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value TEXT NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'GENERAL',
    description VARCHAR(255),
    is_encrypted BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by VARCHAR(100),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_provider_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    key_alias VARCHAR(100) NOT NULL,
    api_key_encrypted TEXT NOT NULL,
    endpoint_url VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    last_tested_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_provider_keys_provider ON ai_provider_keys(provider);

CREATE TABLE IF NOT EXISTS ai_model_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(60) NOT NULL UNIQUE,
    task_name VARCHAR(100) NOT NULL,
    provider VARCHAR(50) NOT NULL DEFAULT 'GEMINI',
    model_name VARCHAR(100) NOT NULL,
    temperature DECIMAL(3,2) NOT NULL DEFAULT 0.20,
    max_tokens INT NOT NULL DEFAULT 2048,
    timeout_seconds INT NOT NULL DEFAULT 30,
    failover_provider VARCHAR(50) NULL,
    failover_model VARCHAR(100) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_model_configs_task_type ON ai_model_configs(task_type);

-- Seed default AI model configurations
INSERT INTO ai_model_configs (task_type, task_name, provider, model_name, temperature, max_tokens, timeout_seconds, failover_provider, failover_model)
VALUES 
('CV_PARSING', 'Trích xuất JSON & Sàng lọc CV', 'GEMINI', 'gemini-2.0-flash', 0.10, 4096, 30, 'GEMINI', 'gemini-1.5-flash'),
('INTERVIEW_GEN', 'Sinh câu hỏi phỏng vấn AI theo Job', 'GEMINI', 'gemini-2.0-flash', 0.50, 2048, 25, 'OPENAI', 'gpt-4o-mini'),
('INTERVIEW_NLP', 'Chấm điểm & Nhận xét trả lời phỏng vấn', 'GEMINI', 'gemini-2.0-flash', 0.20, 3072, 35, 'GEMINI', 'gemini-1.5-pro'),
('CODE_GRADING', 'Đánh giá & Chấm điểm bài thi Coding/Tự luận', 'GEMINI', 'gemini-2.0-flash', 0.10, 2048, 30, 'OPENAI', 'gpt-4o-mini'),
('MATCHING', 'Semantic Matching & Phân tích độ phù hợp', 'GEMINI', 'gemini-2.0-flash', 0.10, 2048, 20, 'GEMINI', 'gemini-1.5-flash')
ON CONFLICT (task_type) DO NOTHING;
