CREATE TABLE IF NOT EXISTS master_notification_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code     VARCHAR(64) NOT NULL,
    type            VARCHAR(64) NOT NULL,
    to_email        VARCHAR(128) NOT NULL,
    status          VARCHAR(32) NOT NULL,
    error_message   TEXT,
    sent_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
