-- V21: Payment Transactions Audit Log & Amount Column Scale for Master DB

-- 1. Increase amount & subtotal scale in invoices for VND figures (e.g. 100M+ VND)
ALTER TABLE invoices
    ALTER COLUMN amount TYPE DECIMAL(15,2),
    ALTER COLUMN subtotal TYPE DECIMAL(15,2);

-- 2. Create payment_transactions table for recording all gateway payment attempts (VNPay, VietQR, etc.)
CREATE TABLE IF NOT EXISTS payment_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT NOT NULL,
    tenant_id           BIGINT NULL,
    transaction_no      VARCHAR(128) NULL,
    txn_ref             VARCHAR(128) NOT NULL,
    payment_gateway     VARCHAR(32) NOT NULL DEFAULT 'VNPAY',
    bank_code           VARCHAR(64) NULL,
    bank_tran_no        VARCHAR(128) NULL,
    card_type           VARCHAR(32) NULL,
    amount              DECIMAL(15,2) NOT NULL,
    currency            VARCHAR(8) NOT NULL DEFAULT 'VND',
    response_code       VARCHAR(32) NULL,
    transaction_status  VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    order_info          VARCHAR(512) NULL,
    pay_date            VARCHAR(32) NULL,
    ip_address          VARCHAR(64) NULL,
    raw_response        TEXT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pt_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pt_invoice_id ON payment_transactions (invoice_id);
CREATE INDEX IF NOT EXISTS idx_pt_txn_ref ON payment_transactions (txn_ref);
CREATE INDEX IF NOT EXISTS idx_pt_transaction_no ON payment_transactions (transaction_no);
CREATE INDEX IF NOT EXISTS idx_pt_status ON payment_transactions (transaction_status);
