-- V25: Click-wrap Legal Consent Audit Logs & Invoice Terms Snapshot (Decree 13/2023/ND-CP & ToS Compliance)

-- 1. Add legal consent snapshot columns to invoices
ALTER TABLE invoices
    ADD COLUMN IF NOT EXISTS terms_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS terms_version VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMP NULL;

-- 2. Create master_consent_logs table for immutable legal click-wrap audit trail
CREATE TABLE IF NOT EXISTS master_consent_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NULL,
    invoice_id      BIGINT NULL,
    actor_name      VARCHAR(255) NOT NULL,
    actor_email     VARCHAR(255) NOT NULL,
    policy_type     VARCHAR(64) NOT NULL,
    policy_version  VARCHAR(32) NOT NULL,
    is_accepted     BOOLEAN NOT NULL DEFAULT TRUE,
    ip_address      VARCHAR(64) NOT NULL,
    user_agent      TEXT NULL,
    consent_context VARCHAR(64) NOT NULL DEFAULT 'SELF_SERVE_CHECKOUT',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mcl_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE SET NULL,
    CONSTRAINT fk_mcl_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_mcl_tenant_id ON master_consent_logs (tenant_id);
CREATE INDEX IF NOT EXISTS idx_mcl_invoice_id ON master_consent_logs (invoice_id);
CREATE INDEX IF NOT EXISTS idx_mcl_actor_email ON master_consent_logs (actor_email);
CREATE INDEX IF NOT EXISTS idx_mcl_created_at ON master_consent_logs (created_at DESC);
