ALTER TABLE tenants ADD COLUMN logo_url VARCHAR(512) NULL;
ALTER TABLE tenants ADD COLUMN website VARCHAR(255) NULL;
ALTER TABLE tenants ADD COLUMN address VARCHAR(512) NULL;
ALTER TABLE tenants ADD COLUMN industry VARCHAR(128) NULL;
ALTER TABLE tenants ADD COLUMN company_size VARCHAR(64) NULL;
ALTER TABLE tenants ADD COLUMN description TEXT NULL;
ALTER TABLE tenants ADD COLUMN is_verified BOOLEAN NOT NULL DEFAULT FALSE;
