ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS billing_email VARCHAR(255) NULL;