-- Table: tenant_usage_daily
-- Daily aggregated resource and AI usage metrics per Tenant
CREATE TABLE IF NOT EXISTS tenant_usage_daily (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL,
    usage_date          DATE NOT NULL,
    cv_parses_count     INT NOT NULL DEFAULT 0,
    ai_voice_seconds    INT NOT NULL DEFAULT 0,
    proctoring_seconds  INT NOT NULL DEFAULT 0,
    storage_bytes       BIGINT NOT NULL DEFAULT 0,
    active_jobs_count   INT NOT NULL DEFAULT 0,
    ai_tokens_consumed  BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_usage_daily UNIQUE (tenant_id, usage_date),
    CONSTRAINT fk_tud_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

-- Table: platform_audit_logs
-- System-level and administrative audit logs for SaaS Landlord
CREATE TABLE IF NOT EXISTS platform_audit_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code         VARCHAR(64) NULL,
    platform_user_id    BIGINT NULL,
    action              VARCHAR(64) NOT NULL,
    level               VARCHAR(16) NOT NULL DEFAULT 'INFO',
    description         TEXT NOT NULL,
    ip_address          VARCHAR(64) NULL,
    metadata_json       TEXT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
