-- Master DB Migration: Table for Enterprise Consultation and Demo Requests
CREATE TABLE IF NOT EXISTS consultation_requests (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name            VARCHAR(255) NOT NULL,
    contact_name            VARCHAR(255) NOT NULL,
    job_title               VARCHAR(255) NULL,
    work_email              VARCHAR(255) NOT NULL,
    phone_number            VARCHAR(64) NULL,
    company_size            VARCHAR(64) NULL,
    request_type            VARCHAR(64) NOT NULL DEFAULT 'DEMO',
    plan_tier               VARCHAR(128) NULL,
    primary_need            TEXT NULL,
    notes                   TEXT NULL,
    status                  VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_consultation_requests_status ON consultation_requests(status);
CREATE INDEX IF NOT EXISTS idx_consultation_requests_email ON consultation_requests(work_email);
CREATE INDEX IF NOT EXISTS idx_consultation_requests_created_at ON consultation_requests(created_at DESC);
