CREATE TABLE IF NOT EXISTS role_permissions (
    id           BIGINT PRIMARY KEY AUTO_INCREMENT,
    `role`       VARCHAR(32)  NOT NULL,
    feature_code VARCHAR(64)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_role_permissions_role_feature (`role`, feature_code)
);

INSERT IGNORE INTO role_permissions (`role`, feature_code)
SELECT v.`role`, v.feature_code
FROM (
    SELECT 'HR' AS `role`, 'DASHBOARD' AS feature_code
    UNION ALL SELECT 'HR', 'JOBS'
    UNION ALL SELECT 'HR', 'APPLICANTS'
    UNION ALL SELECT 'HR', 'CV_SCREENING'
    UNION ALL SELECT 'HR', 'RANKING'
    UNION ALL SELECT 'HR', 'PIPELINE'
    UNION ALL SELECT 'HR', 'ANALYTICS'
    UNION ALL SELECT 'HR', 'ASSESSMENTS'
    UNION ALL SELECT 'HR', 'INTERVIEWS'
    UNION ALL SELECT 'HR', 'SCHEDULES'
    UNION ALL SELECT 'HR', 'NOTIFICATIONS'
    UNION ALL SELECT 'RECRUITER', 'DASHBOARD'
    UNION ALL SELECT 'RECRUITER', 'JOBS'
    UNION ALL SELECT 'RECRUITER', 'APPLICANTS'
    UNION ALL SELECT 'RECRUITER', 'CV_SCREENING'
    UNION ALL SELECT 'RECRUITER', 'RANKING'
    UNION ALL SELECT 'RECRUITER', 'PIPELINE'
    UNION ALL SELECT 'RECRUITER', 'ANALYTICS'
    UNION ALL SELECT 'RECRUITER', 'ASSESSMENTS'
    UNION ALL SELECT 'RECRUITER', 'INTERVIEWS'
    UNION ALL SELECT 'RECRUITER', 'SCHEDULES'
    UNION ALL SELECT 'RECRUITER', 'NOTIFICATIONS'
) v;
