import { useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { humanInterviewApi as api } from "@/api/tenant/humanInterviewApi";
import { getApiErrorMessage } from "@/lib/axios";
import { DetailDialog } from "@/components/ux/DetailDialog";
import { StatusPill } from "@/components/ux/StatusPill";
import { button, muted, panel, primary } from "@/features/tenant/recruiter/matching/components/rankingUi";
import { downloadInterview, statusLabels } from "@/components/ux/humanInterviewUtilities";
const schema = z.object({ start: z.string().min(1), end: z.string().min(1), reason: z.string().trim().min(1).max(2000) }).refine(v => { const start = new Date(v.start).getTime(), end = new Date(v.end).getTime(); return start > Date.now() && end-start >= 900000 && end-start <= 14400000; }, { message: "Chọn lịch tương lai dài 15–240 phút.", path: ["start"] });
export function HumanInterviewActions() {
  const client = useQueryClient(); const [message,setMessage] = useState(""); const [editing,setEditing] = useState<number | null>(null);
  const rows = useQuery({ queryKey: ["human-interviews","mine"], queryFn: api.mine });
  const form = useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema), defaultValues: { start:"",end:"",reason:"" } });
  const mutation = useMutation({ mutationFn: (fn:()=>Promise<unknown>)=>fn(), onSuccess:()=>{void client.invalidateQueries({queryKey:["human-interviews"]});setEditing(null);setMessage("Đã cập nhật lịch phỏng vấn.");}, onError:e=>setMessage(getApiErrorMessage(e)) });
  return <section id="human-interviews" className="scroll-mt-24 space-y-4"><header><h1 className="text-2xl font-semibold">Lịch phỏng vấn trực tiếp</h1><p className={`mt-1 ${muted}`}>Xác nhận lịch phỏng vấn trực tiếp và đề nghị đổi giờ với nhà tuyển dụng.</p></header>
    {message && <p role="status">{message}</p>}{rows.isPending && <p role="status">Đang tải lịch…</p>}{rows.error && <p role="alert">{getApiErrorMessage(rows.error)} <button onClick={()=>void rows.refetch()}>Thử lại</button></p>}
    <div className={`${panel} space-y-4`}>{rows.data?.length === 0 && <p>Chưa có lịch phỏng vấn.</p>}{rows.data?.map(row=><article key={row.id} className="space-y-3 rounded-2xl border border-[var(--color-border-default)] p-4"><div className="flex justify-between gap-3"><h3 className="text-lg font-semibold">{row.jobTitle}</h3><StatusPill status={row.status} label={statusLabels[row.status]}/></div><p>{new Date(row.start).toLocaleString("vi-VN")} – {new Date(row.end).toLocaleTimeString("vi-VN")}</p><p className={muted}>Hội đồng: {row.participants.map(p=>p.name).join(", ")}</p>{row.mode === "ONLINE" && row.meetingUrl ? <a className="underline text-[var(--color-primary)]" href={row.meetingUrl} target="_blank" rel="noreferrer">Mở link meeting</a> : <p>{row.location}</p>}<p>{row.configuration.notes}</p>{row.status === "RESCHEDULE_REQUESTED" && <p>Đã đề nghị đổi giờ: {row.configuration.rescheduleReason}</p>}<div className="flex flex-wrap gap-2">{row.status === "PROPOSED" && new Date(row.start).getTime()>Date.now() && <button className={primary} disabled={mutation.isPending} onClick={()=>mutation.mutate(()=>api.confirm(row.id))}>Xác nhận tham dự</button>}{["PROPOSED","CONFIRMED","RESCHEDULE_REQUESTED"].includes(row.status) && new Date(row.start).getTime()>Date.now() && <button className={button} onClick={()=>{form.reset();setEditing(row.id);}}>Đề nghị đổi giờ</button>}<button className={button} onClick={()=>void api.calendar(row.id).then(blob=>downloadInterview(blob,`interview-${row.id}.ics`)).catch(e=>setMessage(getApiErrorMessage(e)))}>Tải lịch ICS</button><Link className={button} to={`/applications/${row.applicationId}`}>Chi tiết đơn</Link></div></article>)}</div>
    <DetailDialog open={editing !== null} title="Đề nghị đổi lịch" onClose={()=>setEditing(null)}><form className="space-y-4" onSubmit={form.handleSubmit(v=>mutation.mutate(()=>api.requestChange(editing!,{start:new Date(v.start).toISOString(),end:new Date(v.end).toISOString(),reason:v.reason})))}><label className="block">Bắt đầu<input className="ml-3 rounded border p-2" type="datetime-local" {...form.register("start")}/></label><label className="block">Kết thúc<input className="ml-3 rounded border p-2" type="datetime-local" {...form.register("end")}/></label><textarea className="w-full rounded border p-2" placeholder="Lý do đổi lịch" {...form.register("reason")}/>{Object.values(form.formState.errors).map((e,i)=><p key={i} role="alert">{e.message}</p>)}<button className={primary} disabled={mutation.isPending}>Gửi đề nghị</button><p className={muted}>Lịch hiện tại được giữ cho đến khi nhà tuyển dụng duyệt và dời lịch.</p></form></DetailDialog>
  </section>;
}
