import { useState } from "react";
import { Filter, Play, ShieldAlert } from "lucide-react";
import type { TenantInfo } from "@/api/master/masterAdminApi";

type Props = { tenants: TenantInfo[] };

export function TrafficIngressInspector({ tenants }: Props) {
  const [host, setHost] = useState(tenants[0] ? `${tenants[0].subdomain}.smarthire.top/api` : "tenant.smarthire.top/api");
  const [probedHost, setProbedHost] = useState<string | null>(null);
  const identifier = (probedHost ?? host).split(".")[0].replace(/^https?:\/\//, "");
  const tenant = tenants.find((item) => item.subdomain === identifier || item.code === identifier);
  const allowed = tenant?.status === "ACTIVE";
  const status = tenant ? (allowed ? 200 : 403) : 404;

  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_4px_14px_-8px_rgba(15,23,42,0.16)]"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-700"><Filter className="size-5"/></span><div><h2 className="font-semibold text-slate-950">Traffic Ingress Inspector</h2><p className="mt-1 text-xs text-slate-500">Mô phỏng quyết định resolve tenant từ host bằng dữ liệu Master Registry hiện tại.</p></div></div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-bold uppercase text-amber-700">UI simulation · chưa có probe API</span></div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><label className="flex min-h-11 flex-1 items-center rounded-xl border border-slate-200 bg-slate-50 px-3"><span className="mr-3 text-[10px] font-bold uppercase text-blue-700">Host</span><input value={host} onChange={(event) => setHost(event.target.value)} className="min-w-0 flex-1 bg-transparent font-mono text-xs outline-none" aria-label="Host cần kiểm tra"/></label><button type="button" onClick={() => setProbedHost(host.trim())} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white hover:bg-blue-700"><Play className="size-4"/>Probe mô phỏng</button></div>{probedHost && <div className="mt-4 rounded-xl bg-slate-950 p-4 font-mono text-xs leading-6 text-slate-200"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-700 pb-3"><span>GATEWAY EGRESS ENVELOPE</span><span className={status === 200 ? "rounded bg-emerald-100 px-2 text-emerald-800" : "rounded bg-rose-100 px-2 text-rose-800"}>HTTP/1.1 {status} {status === 200 ? "ROUTED" : status === 403 ? "FORBIDDEN" : "NOT FOUND"}</span></div><div className="mt-3 text-slate-300">x-smarthire-tenant-id: {tenant?.id ?? "UNRESOLVED"}<br/>x-smarthire-routing-guard: {allowed ? "ALLOWED_ACTIVE" : tenant ? "DENIED_ADMIN_HOLD" : "DENIED_UNKNOWN_TENANT"}<br/>x-smarthire-pool-routed: {allowed ? tenant?.dbName : "NONE (0 connections)"}</div><div className="mt-3 rounded-lg bg-white p-3 text-rose-700">{JSON.stringify(allowed ? { status: "ACTIVE", tenant: tenant?.code, routed: true } : { error: tenant ? "TENANT_ACCESS_RESTRICTED" : "TENANT_NOT_FOUND", tenant: identifier, status: tenant?.status ?? "UNKNOWN", retryable: false }, null, 2)}</div><div className="mt-3 flex items-center gap-2 text-slate-400"><ShieldAlert className="size-4"/>Không gửi request thật và không truy vấn tenant database.</div></div>}</section>;
}
